### ISSUE TITLE
PopUp builder widgets rotate away from markers on Pinch rotate

### ISSUE THREAD

**Issue by MaxiStefan** [lpongetti/flutter_map_marker_cluster#200]
Basically title. Display marker popups, rotate the screen and the popups fly away. I though it might be yet again a MobileLayerTransformer issue but the Stack in marker_cluster_layer.dart is wrapped with it and the flutter_map_marker_popup also has it wrapped around its own layers.

**Comment by tratteo** [comment]
Encountering the same error, I tried looking at the code but didn't find the problem @lpongetti

**Comment by tratteo** [comment]
I fixed it and made a pull request (#201) @MaxiStefan.
The problem was indeed the `MobileLayerTransformer`. The `PopupLayer` was wrapped in one while it already had its own interally, that caused transformation conflicts. While waiting for @lpongetti to mege the PR, you can depend on my fork. Thanks for the hint!
Cheers 👍🏼

**Comment by MaxiStefan** [comment]
Nice, congrats for finding it!

**Comment by lpongetti** [comment]
thanks @tratteo
