### ISSUE TITLE
Implement the package with flutter_map_marker_popup

### ISSUE THREAD

**Issue by franciscogodoy97** [lpongetti/flutter_map_marker_cluster#206]
I am having problems implementing the flutter_map_marker_popup with the cluster, I want that when I click on the marker there will be a popup with the package mentioned above

These are the versions I have

flutter_map_marker_popup: ^6.1.2
flutter_map_marker_cluster: ^1.3.4

please your help

**Comment by Pratima116** [comment]
I am using same versions mentioned above and adding PopupMarkerLayer with empty markers worked for me. Also instead of wrapping Marker Icon with GestureDetector for marker tap function, I used onMarkerTap inside MarkerClusterLayerOptions to handle the onTap functions.

<img width="600" alt="Screenshot 2024-01-24 at 12 25 30 PM" src="https://github.com/lpongetti/flutter_map_marker_cluster/assets/111721526/c890cba4-855c-474a-9445-1ee4aea88398">

**Comment by franciscogodoy97** [comment]
When I do this, I get the following error:

Multiple widgets used the same GlobalKey.
The key [GlobalKey#3ed9b] was used by multiple widgets. The parents of those widgets were:
- Align(alignment: Alignment.bottomCenter, dependencies: [Directionality], renderObject: RenderPositionedBox#5c0f2)
- Align(alignment: Alignment.bottomCenter, dependencies: [Directionality], renderObject: RenderPositionedBox#1bd43)
A GlobalKey can only be specified on one widget at a time in the widget tree.
