### ISSUE TITLE
Marker on tap does not work

### ISSUE THREAD

**Issue by 121601571** [lpongetti/flutter_map_marker_cluster#21]
When using MarkerClusterLayerOptions, onpressed worked for the cluster, but the marker's onTap does not work...

**Comment by lpongetti** [comment]
Try to use different widget

**Comment by rorystephenson** [comment]
@121601571 are you using a GestureDetector in the Marker's build Widget? I'm pretty new to flutter but from what I understand only one GestureDetector gets triggered per gesture (tap in this case) and since the Marker onTap uses a GestureDetector, if you have a GestureDetector in your Marker's build Widget it will override the onTap behaviour.

My only solution so far has been to modify flutter_map_marker_cluster to add a onMarkerTap callback to the options and to trigger this in _onMarkerTap.
