### ISSUE TITLE
Popup positioning in spiderfy function 

### ISSUE THREAD

**Issue by claudiosul** [lpongetti/flutter_map_marker_cluster#211]
First I would like to thank you for this great package.  I noticed that when a cluster is opened using the spiderfy function, the inserted popups remain positioned at their original point within the map, and do not follow the alignment set with respect to the marker.  please fix the issue thanks

**Comment by ProgUser145** [comment]
Same problem here. When spiderfying the map the location of the markers is not the correct one, but they are simply spidered around the center of the cluster

**Comment by Azzeccagarbugli** [comment]
Hey @claudiosul, @ProgUser145 and @lpongetti. 

Yesterday, I was working a bit [on my fork](https://github.com/Azzeccagarbugli/flutter_map_marker_cluster) on the `package` to implement _(or fix)_, the feature regarding the `_onMarkerTapInsideCluster` and it is somehow working as you can see here _(you can try it out by running the example app)_.

| **Before** 	| **After** 	|
|:---:	|:---:	|
| ![Screenshot](https://github.com/lpongetti/flutter_map_marker_cluster/assets/16477661/d0f6595c-1561-4a88-98a7-1b73a5abcfdf)| ![Screenshot](https://github.com/lpongetti/flutter_map_marker_cluster/assets/16477661/aa1db759-6139-431e-a35d-e638a78c43da)|

---

The only thing that is not still working, and I'm a bit buzzed about, is how to place the marker correctly when a **rotation** or a **zoom** has taken place since those gestures would completely put off the popup on marker _(I guess it's a problem regarding the `mapCalulcator` function pointToLatLng but I can't figure it out)_.

Feel free to help me out and @lpongetti maybe let me know if you want me to open a **PR** for this.

Thanks a lot and have a nice day ✨
